org: foobardude
app: alexa-dynamo-serverless
service: test-http
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:304560344138:table/TaskTable

functions:
  mediciPatient:
    handler: lambda/custom/index.handler
    events:
      - alexaSkill: amzn1.ask.skill.611b5779-0ece-4f49-9329-13033a19664e

  hello:
    handler: lambda/custom/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  createTask:
    handler: lambda/custom/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post
  getTasks:
    handler: lambda/custom/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  getTask:
    handler: lambda/custom/getTask.getTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: get
  updateTask:
    handler: lambda/custom/updateTask.updateTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: put
  deleteTask:
    handler: lambda/custom/deleteTask.deleteTask
    events:
      - httpApi:
          path: /tasks/{id}
          method: delete

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dynamodb-starter
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: movieTitle
            KeyType: RANGE
